all:
	g++ *.cpp -o game -std=c++11 -lglfw3 -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lrt -lGLEW -lGL -lglut -lGLU -lm -ldl -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lXinerama  -lXext -lXcursor -lXrender -lXfixes  -lXau -lXdmcp

